version: 2.1

orbs:
  browser-tools: circleci/browser-tools@2.0.0

jobs:
  build:
    docker:
      - image: cimg/base:current
    parallelism: 30
    resource_class: medium
    steps:
      - checkout
      - run:
          command: |
              # Need sudo to modify system files
              # sudo sed -i 's|http://archive.ubuntu.com|http://us-east-1.ec2.archive.ubuntu.com|g' /etc/apt/sources.list
              # sudo sed -i 's|http://security.ubuntu.com|http://us-east-1.ec2.archive.ubuntu.com|g' /etc/apt/sources.list
              # Update package lists with new sources
              sudo apt-get update
          name: update ubuntu package
      - browser-tools/install_chrome
      - browser-tools/install_chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check chrome install
