
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.6
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - browser-tools/install-chrome:
          chrome-version: 120.0.6099.71
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check chrome install
