version: 2.1

orbs:
  browser-tools: circleci/browser-tools@2.0.0

jobs:
  build:
    docker:
      - image: cimg/base:current
    parallelism: 30
    resource_class: medium
    steps:
      - checkout
      - browser-tools/install_chrome
      - browser-tools/install_chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check chrome install
